version: '3'

services:
  campaign-communicate-consumer:
    container_name: campaign-communicate-consumer
    image: flowerappengorg/campaign-communicate-consumer:0.1.0  
    environment:
      KAFKA_HOST: 'kafka:9092'
    depends_on:
      kafka:
        condition: service_healthy
  campaign-send-email-consumer:
    container_name: campaign-send-email-consumer
    image: flowerappengorg/campaign-send-email-consumer:0.1.0  
    environment:
      KAFKA_HOST: 'kafka:9092'
    depends_on:
      kafka:
        condition: service_healthy
  campaign-api: 
    tty: true
    stdin_open: true
    container_name: campaign-api
    image: flowerappengorg/campaign-api:0.1.0 
    restart: always
    environment:
      PORT: "3030"
      CORS_HOST: "*"
      KAFKA_HOST: "kafka:9092"
    ports:
      - 3030:3030    
  kafka:
    container_name: campaign-kafka-app
    image: 'bitnami/kafka:3.4.1'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: ["CMD-SHELL", "echo 'test-message' | kafka-console-producer.sh --broker-list kafka:9092 --topic health-check-topic && kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic health-check-topic --from-beginning --max-messages 1 | grep 'test-message'"]
      interval: 15s
      timeout: 10s
      retries: 5  
    volumes:
      - ./kafka-persistence:/bitnami/kafka
